name: AWS Destroy
on:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  AWS-Destroy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::211125721747:role/git-action-demo
          role-session-name: my-session
          aws-region: ap-south-1

      # Initialize
      - name: Init Phase
        id: init-destroy
        run: terraform init

      # Destroy
      - name: Destroy Phase
        id: destroy
        run: terraform destroy -auto-approve
