name: Terraform Module Versioned Packaging and Upload

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  versioned-upload:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125721747:role/git-action-demo
          aws-region: ap-south-1 
          role-session-name: terraform-module-versioning

      - name: Install Tools
        run: sudo apt-get install -y zip jq

      - name: Determine Next Version
        id: version
        run: |
          # List current versions in the folder
          MODULE_FOLDER="modules/network/"
          BUCKET_NAME="mymsplanet01-terraform"
          VERSIONS=$(aws s3 ls s3://$BUCKET_NAME/$MODULE_FOLDER | awk '{print $4}' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sort -V)

          # Get the latest version
          LATEST_VERSION=$(echo "$VERSIONS" | tail -n 1 || echo "0.0.0")
          echo "Latest version: $LATEST_VERSION"

          # Increment the version (e.g., 0.2.2 -> 0.2.3)
          NEW_VERSION=$(echo $LATEST_VERSION | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo "Next version: $NEW_VERSION"

          # Export new version
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create Versioned ZIP
        run: |
          MODULE_NAME="terraform-module-${{ env.NEW_VERSION }}"
          zip -r ${MODULE_NAME}.zip ./*
          echo "MODULE_NAME=${MODULE_NAME}.zip" >> $GITHUB_ENV

      - name: Upload to S3
        run: |
          MODULE_FOLDER="module/network/"
          aws s3 cp ${{ env.MODULE_NAME }} s3://my-terraform-modules/$MODULE_FOLDER${{ env.MODULE_NAME }}
        env:
          AWS_REGION: ap-south-1
